### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by adamstallard** [CirclesUBI/domain-model#2]
What's the purpose of these authentication methods if the user is presupposed to hold an ethereum account?  Are you creating ethereum accounts and holding private keys using a central service?  Why not let the user manage this?  Why do you need to collect email addresses, google and facebook accounts?  Why not let them unlock their circles account (ethereum private key) locally?

>●	A user can authenticate through any of the authentication methods that they have enabled:
○	Native login, using their primary e-mail and a password.
○	Through their Google or Facebook account.
○	Through uPort, a decentralized identity provider implemented on the Ethereum blockchain.

**Comment by edzillion** [comment]
I am going to close this as it is superseded.
